### ISSUE TITLE
what is the purpose of this lib?

### ISSUE THREAD

**Issue by fukemy** [shoaib2527/react-native-screen-wrapper#1]
As title, I want to ask some question:
 1. Does this lib work as something like ViewPager
 2. It's look like I can wrap any screen inside wrapperview, does this took more performance(because I think screen will init right after wrapperview inited)
 
  Thanks

**Comment by shoaib2527** [comment]
Ans:
1. No, ViewPager is a different thing where we can swipe between Components (Pages).
2. It doesn't improve performance.

This package actually removes redundant code which we need to have on each Navigation Screen e.g Fragment, StatusBar, SafeAreaView, ScrollView, KeyboardAwareScrollView. Visit this brief article to see it in action. https://medium.com/@shoaib.ahmed47564/what-is-react-native-screen-wrapper-77de4f124cbc
